#!/usr/bin/env python3
"""
Daily News Report Generator
Fetches top stories from Google News RSS feed and generates a formatted report.
Can optionally email the report using Resend (free tier: 100 emails/day).
"""

import feedparser
import requests
from datetime import datetime
from pathlib import Path
import re
import os
import sys


def fetch_google_news_rss(country='US', language='en', num_stories=10):
    """
    Fetch top stories from Google News RSS feed.

    Args:
        country: Country code (e.g., 'US', 'GB', 'CA')
        language: Language code (e.g., 'en', 'es', 'fr')
        num_stories: Maximum number of stories to return

    Returns:
        List of news items with title, link, source, and published date
    """
    rss_url = f"https://news.google.com/rss?hl={language}-{country}&gl={country}&ceid={country}:{language}"

    try:
        response = requests.get(rss_url, timeout=30)
        response.raise_for_status()
        feed = feedparser.parse(response.content)

        stories = []
        for entry in feed.entries[:num_stories]:
            # Parse source from title if available
            title = entry.get('title', 'No title')
            link = entry.get('link', '')
            published = entry.get('published', 'Unknown date')

            # Extract source from title (often formatted as "Title - Source")
            source = "Unknown"
            if ' - ' in title:
                parts = title.rsplit(' - ', 1)
                title = parts[0]
                source = parts[1]

            stories.append({
                'title': title,
                'source': source,
                'link': link,
                'published': published
            })

        return stories
    except requests.RequestException as e:
        print(f"Error fetching news: {e}")
        return []


def generate_news_report(stories, output_format='markdown'):
    """
    Generate a formatted news report from the stories.

    Args:
        stories: List of news story dictionaries
        output_format: 'markdown' or 'text'

    Returns:
        Formatted report string
    """
    today = datetime.now().strftime("%A, %B %d, %Y")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if output_format == 'markdown':
        lines = [
            f"# Daily News Report",
            f"",
            f"**Date:** {today}  ",
            f"**Generated:** {timestamp}",
            f"",
            f"## Top Stories",
            f"",
        ]

        for i, story in enumerate(stories, 1):
            lines.extend([
                f"### {i}. {story['title']}",
                f"",
                f"- **Source:** {story['source']}",
                f"- **Published:** {story['published']}",
                f"- **Link:** {story['link']}",
                f"",
            ])

        lines.extend([
            f"---",
            f"",
            f"*Report generated by Daily News Script*",
        ])

    else:  # plain text
        lines = [
            f"DAILY NEWS REPORT",
            f"{'=' * 50}",
            f"Date: {today}",
            f"Generated: {timestamp}",
            f"",
            f"TOP STORIES",
            f"{'-' * 50}",
            f"",
        ]

        for i, story in enumerate(stories, 1):
            lines.extend([
                f"{i}. {story['title']}",
                f"   Source: {story['source']}",
                f"   Published: {story['published']}",
                f"   Link: {story['link']}",
                f"",
            ])

        lines.extend([
            f"{'=' * 50}",
            f"Report generated by Daily News Script",
        ])

    return "\n".join(lines)


def save_report(report, output_dir=None, filename=None):
    """
    Save the report to a file.

    Args:
        report: The report content string
        output_dir: Directory to save the file (default: same as script)
        filename: Custom filename (default: daily_news_YYYY-MM-DD.md)

    Returns:
        Path to the saved file
    """
    if output_dir is None:
        output_dir = Path(__file__).parent
    else:
        output_dir = Path(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    if filename is None:
        date_str = datetime.now().strftime("%Y-%m-%d")
        filename = f"daily_news_{date_str}.md"

    filepath = output_dir / filename

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)

    return filepath


def send_email_resend(report_content, to_email, from_email="news@dailyreport.local", subject=None):
    """
    Send the report via email using Resend (free tier: 100 emails/day).

    Args:
        report_content: The report content (Markdown or plain text)
        to_email: Recipient email address
        from_email: Sender email address (must be verified in Resend)
        subject: Email subject (default: auto-generated with date)

    Returns:
        True if sent successfully, False otherwise
    """
    try:
        import resend
    except ImportError:
        print("Resend library not installed. Install with: pip install resend")
        return False

    # Get API key from environment variable or file
    api_key = os.environ.get("RESEND_API_KEY")

    # If not in environment, try reading from file
    if not api_key:
        key_file_path = r"C:\Users\andre\Downloads\resend_api_key_plain_text.txt"
        try:
            with open(key_file_path, 'r', encoding='utf-8') as f:
                api_key = f.read().strip()
        except FileNotFoundError:
            pass  # Will show error below with instructions

    if not api_key:
        print("ERROR: RESEND_API_KEY not found")
        print("\nTo set up:")
        print("1. Get your API key from https://resend.com")
        print("2. Save it to: C:\\Users\\andre\\Downloads\\resend_api_key_plain_text.txt")
        print("   OR set environment variable:")
        print("   Windows PowerShell: $env:RESEND_API_KEY=\"re_xxxxxx\"")
        return False

    resend.api_key = api_key

    if subject is None:
        today = datetime.now().strftime("%A, %B %d, %Y")
        subject = f"Daily News Report - {today}"

    # Convert markdown to simple HTML for email
    html_content = markdown_to_html(report_content)

    try:
        params = {
            "from": from_email,
            "to": to_email,
            "subject": subject,
            "html": html_content,
            "text": report_content,  # Plain text fallback
        }

        email = resend.Emails.send(params)
        print(f"Email sent successfully! ID: {email.get('id', 'N/A')}")
        return True
    except Exception as e:
        error_msg = str(e)
        print(f"Failed to send email: {error_msg}")

        # Provide helpful guidance for common errors
        if "domain is not verified" in error_msg.lower():
            print("\n---")
            print("Note: On Resend's free tier, you can only send TO the email")
            print("address you signed up with (the account owner).")
            print("\nTo send to andrew123daly@gmail.com, either:")
            print("1. Sign up for Resend using andrew123daly@gmail.com")
            print("2. Verify a domain at https://resend.com/domains")
            print("3. Upgrade to a paid Resend plan")
            print("---")

        return False


def markdown_to_html(markdown_text):
    """
    Simple markdown to HTML converter for email.

    Args:
        markdown_text: Markdown formatted text

    Returns:
        HTML formatted text
    """
    html = markdown_text

    # Headers
    html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)

    # Bold
    html = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', html)
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)

    # Links
    html = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', html)

    # Lists
    html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
    html = re.sub(r'(<li>.+</li>\n)+', r'<ul>\g<0></ul>', html)

    # Line breaks
    html = re.sub(r'\n\n', r'<br><br>', html)
    html = re.sub(r'\n', r'<br>', html)

    # Horizontal rule
    html = re.sub(r'^---$', r'<hr>', html, flags=re.MULTILINE)

    # Wrap in basic HTML structure
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }}
        h2 {{ color: #444; margin-top: 30px; }}
        h3 {{ color: #555; }}
        ul {{ padding-left: 20px; }}
        li {{ margin-bottom: 5px; }}
        a {{ color: #007bff; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 30px 0; }}
        .footer {{ color: #888; font-size: 0.9em; margin-top: 30px; }}
    </style>
</head>
<body>
{html}
</body>
</html>"""

    return html


def main():
    """Main function to generate daily news report."""
    print("Fetching top stories from Google News...")

    # Fetch news stories
    stories = fetch_google_news_rss(country='US', language='en', num_stories=10)

    if not stories:
        print("Failed to fetch news stories.")
        return 1

    print(f"Successfully fetched {len(stories)} stories.")

    # Generate report
    report = generate_news_report(stories, output_format='markdown')

    # Save to file
    filepath = save_report(report)
    print(f"Report saved to: {filepath}")

    # Also print to console
    print("\n" + "=" * 50)
    print("DAILY NEWS REPORT PREVIEW")
    print("=" * 50)
    print(report[:2000] + "..." if len(report) > 2000 else report)

    # Send email - using Resend's onboarding address (for testing)
    # After verifying your domain, you can use your own from address
    to_email = os.environ.get("DAILY_NEWS_EMAIL", "andrew123daly@gmail.com")

    print("\n" + "=" * 50)
    print("SENDING EMAIL")
    print("=" * 50)
    print(f"To: {to_email}")

    # Resend's testing from address (works without domain verification)
    from_email = "onboarding@resend.dev"

    send_email_resend(report, to_email, from_email=from_email)

    return 0


if __name__ == "__main__":
    exit(main())
